include(install_vcpkg)

include(install_vulkan)
include(install_volk)
include(install_vma)
include(install_glfw)
include(install_imgui)
include(install_tbb)
include(install_embree)
include(install_assimp)

macro(link_all _target)
    link_vulkan(${_target})
    link_volk(${_target})
    link_vma(${_target})
    link_glfw(${_target})
    link_imgui(${_target})
    link_tbb(${_target})
    link_embree(${_target})
    link_assimp(${_target})
endmacro()