include(install_vcpkg)

include(install_vulkan)
include(install_volk)
include(install_vma)
include(install_slang)
include(install_glfw)
include(install_imgui)
include(install_tbb)
include(install_embree)
include(install_assimp)
include(install_freeimage)
include(install_spdlog)
include(install_rapidjson)

macro(link_all _target)
    link_vulkan(${_target})
    link_volk(${_target})
    link_vma(${_target})
    link_slang(${_target})
    link_glfw(${_target})
    link_imgui(${_target})
    link_tbb(${_target})
    link_embree(${_target})
    link_assimp(${_target})
    link_freeimage(${_target})
    link_spdlog(${_target})
    link_rapidjson(${_target})
endmacro()